require:
- rubocop-minitest
- rubocop-performance
- rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics:
  Enabled: false

Minitest/AssertEqual:
  Enabled: false
Minitest/MultipleAssertions:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Documentation:
  Enabled: false
Style/InfiniteLoop:
  Enabled: false
Style/Next:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
