#!/bin/sh

set -eu

test -d "/usr/share/rbenv/shims" && {
  export PATH="/usr/share/rbenv/shims:$PATH"
  export RBENV_VERSION="2.4.1"
}

set -x
git log -n 1 HEAD | cat
ruby -v
bundle -v
set +x

git clean -fd

script/bootstrap
bundle exec rake
