name: Ruby
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
        - "2.7"
        - "3.0"
        - "3.1"
        - "3.2"
        - "3.3"
        - head
        gemfile-path:
        - Gemfile
        - gemfiles/faraday_0.gemfile
        - gemfiles/faraday_1.gemfile
        - gemfiles/faraday_2.gemfile
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile-path }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        rubygems: latest
        bundler: latest
        bundler-cache: true
        cache-version: 1
    - name: Run tests
      run: bin/test
